import './globals.css'
import {Alata, Open_Sans } from 'next/font/google'
import  Navbar  from '@/Components/Heading/Navbar'
import Heading from '@/Components/Heading/Heading'
import Footer from '@/Components/Footer/Footer'

const open_sans = Open_Sans({subsets: ['latin'], weight: '500', style: ['italic', 'normal']})
const alata = Alata({subsets: ['latin'], weight:'400'})

export const metadata = {
  title: 'UTS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${open_sans.variable} ${alata.variable}`}>
        <Heading />
        {children}
        <Footer address="200 Frank Lewis Dr, Roswell, GA 30075" copyright="© Unique Therapy Services LLC" phoneNumber="770-641-9239"/>
      </body>
    </html>
  );
}